pipeline {
    agent any
    stages {
        stage('Run test') {
            steps {
                sh"./mvnw clean install"
                script{
                }
            }
        }

    }
}